### ISSUE TITLE
Dataset requested

### ISSUE THREAD

**Issue by fj-morales** [nert-nlp/pastrie#1]
Hi all, 

I would like to request the PASTRIE dataset accompanying the paper "PASTRIE: A Corpus of Prepositions Annotated with Supsersense Tags in Reddit International English".

Thanks for reply.

**Comment by nschneid** [comment]
Thanks for your interest! We are ironing out some format issues and will post it this week.

**Comment by mkranzlein** [comment]
Hi @fj-morales ,

The initial release is out!
